### ISSUE TITLE
My calendar is suddenly blank

### ISSUE THREAD

**Issue by rictic** [technoweenie/seinfeld#1]
I've enjoyed having http://calendaraboutnothing.com/~rictic as my homepage, to encourage me to contribute and commit code frequently.  However a couple of weeks ago it was suddenly blank, no X's on any days, even ones that used to be X'd out.

I'm still committing, but now my calendar thinks that I'm lazy.  Any ideas why?

**Comment by technoweenie** [comment]
Closing this... apparently ignoring the problem worked :)
