### ISSUE TITLE
Calendar is not Xing off days

### ISSUE THREAD

**Issue by pydanny** [technoweenie/seinfeld#14]
Love the site!

However, while I've maintained my own work, it's not showing up on the Calendar. See me at:
- http://calendaraboutnothing.com/~pydanny

I'm not the only one:
- http://calendaraboutnothing.com/~tombell

**Comment by bhb** [comment]
Which days are incorrect? On the first calendar, I see every day marked except today. On the second one, I see every day marked except yesterday and today.

**Comment by pydanny** [comment]
Oddly enough, all looks good now. Next time I'll take screen shots. Thanks for the response and the service! :)

**Comment by bhb** [comment]
No problem :)
