### ISSUE TITLE
Not updating my score

### ISSUE THREAD

**Issue by pydanny** [technoweenie/seinfeld#15]
I've been diligently working but the site is not updating me at all. I'm still at 60 days and have been stuck there for a week. I've got screen captures if you want them.

**Comment by technoweenie** [comment]
It's been reported.  Still trying to find time to look at it.

**Comment by pydanny** [comment]
Thanks! Your project is awesome. I know the feeling about time. If I had time I would learn Ruby/Sinatra. :D

**Comment by pydanny** [comment]
My score is updated. Thanks! You guys rock!
