### ISSUE TITLE
infinite redirects after sign-in to github

### ISSUE THREAD

**Issue by jperville** [technoweenie/seinfeld#18]
Hello,

I tried to sign up for "calendaraboutnothing", but after successful login to github (and allow the CAN application) I am redirected in an infinite loop. Here is how it looks like in the logs:

<pre>
GET http://calendaraboutnothing.com/edit # 302 Location https://github.com/login/oauth/authorize?client_id=2a84dd9e41f75f9b48d7&redirect_uri=http%3A%2F%2Fcalendaraboutnothing.com%2Fauth%2Fcallback&type=web_server
# while true do
GET https://github.com/login/oauth/authorize?client_id=2a84dd9e41f75f9b48d7&redirect_uri=http%3A%2F%2Fcalendaraboutnothing.com%2Fauth%2Fcallback&type=web_server # 302 Location http://calendaraboutnothing.com/auth/callback?code=c5219915456fecd560dc
GET http://calendaraboutnothing.com/auth/callback?code=c5219915456fecd560dc # 302 Location  http://calendaraboutnothing.com/edit
GET http://calendaraboutnothing.com/edit # 302...
# end
</pre>

**Comment by dennmart** [comment]
It seems the Github API response after authenticating via OAuth is slightly different than the app expects. I created a pull request (Issue #19) that deals with this.

**Comment by jperville** [comment]
Thank you very much @dennmart.

**Comment by relrod** [comment]
+1, would like to sign up - any chance #19 can be pushed live?

**Comment by elia** [comment]
+1

**Comment by kytrinyx** [comment]
+1

**Comment by zerovox** [comment]
+1 
I'd like to sign up too but can't currently

**Comment by relrod** [comment]
FWIW, I have an instance running on OpenShift with (only) this bug fixed (Everything else is the same as upstream, only the patch in #19 has been applied), that some friends and I use.

If anyone would like to use it as well, feel free.
URL is http://can.tenthbit.net/

**Comment by technoweenie** [comment]
All set.  Sorry about the huge delay in this!  Thanks for the patch.
