### ISSUE TITLE
This week says 'slacked', but current streak is still current

### ISSUE THREAD

**Issue by kytrinyx** [technoweenie/seinfeld#21]
On [my calendar](http://calendaraboutnothing.com/~kytrinyx) the last red `X` is on Saturday, though I have numerous commits both on [Sunday](https://github.com/kytrinyx/csi-ruby/commits/master) and [Monday](https://github.com/bengler/pebbles-uid/commits/master)

I'd be happy to dig into it if there's a problem, but I wanted to check with you first in case I'm just missing something really silly.

**Comment by callumacrae** [comment]
Yeah, it looks like they haven't ran the script to update everything for a few days.

c'mon, guys! xD

**Comment by technoweenie** [comment]
I may just kill seinfeld (er the app, not the hilarious comedian).  Things keep failing, and I don't have time to look at it.

**Comment by callumacrae** [comment]
:'(
