### ISSUE TITLE
Time zone bug?

### ISSUE THREAD

**Issue by bhb** [technoweenie/seinfeld#5]
When I look at anyone's calendar after 8PM Mountain time, all calendars show the current date as being tomorrow instead of today.

As a result, if I push to my open source project after 8PM, it says I did not commit today and I break my streak. Bummer.

**Comment by technoweenie** [comment]
It's not a bug, everyone's just set to UTC.  I'm currently looking for patches for an admin page, but I can update your timezone manually if you like.

**Comment by bhb** [comment]
Ah, I see. 

Since the GitHub account page includes a location, I wonder if it would be able to get that information and use it as the time zone. Of course, if it's not set, CAN could revert to the current default.

Then again, an admin console would probably be useful for other things.

**Comment by technoweenie** [comment]
Yea, this is just a super hobby project for me.  I'll just set your timezone if you want.

**Comment by bhb** [comment]
Cool, I understand. I hopefully will get a chance to look around in the source and see if there is a simple patch sometime soon.

In any case, I'll take you up on your offer to manually set my timezone. Please set it to Mountain Time. Thanks!

**Comment by paulbaumgart** [comment]
Hi technoweenie-- not particularly urgent, but if you have a free moment to set mine to Pacific Time, I'd appreciate it. Thanks!

**Comment by bhb** [comment]
Rick - I know you're busy, but if you have some time, can you please check that I'm set to U.S. Mountain time? [This commit](http://github.com/bhb/tack/commit/9d51070a3e1571e4cd73882d932409f046877b59) was on "Sat Aug 14 18:20:17 2010 -0600" (in other words, 4:20PM Mountain time), but it shows up on CAN as on the 15th.

I really appreciate it.

Ben

**Comment by bhb** [comment]
This is now resolved. Each user's time zone is determined from the "Location" field set in his or her GitHub profile.
